#!/bin/sh

# Author : James Stoup
# Email  : james.stoup@bylight.com


# A simple git hook to ensure we are adding the time and comment flags to each git subject

# subject line
# sub=`head -1 $1`
# sub_length=${#sub}  # for later if we want to cap line length

# if echo "$sub" | grep -qEi "(^james|^dev|^org) " ; then
#     exit 0
# fi

# # want to ignore merges
# if echo "$sub" | grep -iqE "^Merge branch" ; then
#     echo "Detected merge"
# 	exit 0
# fi

# # want to ignore merges
# if echo "$sub" | grep -iqE "^Merge remote" ; then
# 	exit 0
# fi

# # Check for a comment flag first
# if ! echo $sub | grep -q '#comment ' ; then
#     echo "ABORTING - #comment flag missing in subject"
#     exit 1
# fi

# # Check for a time flag next
# if ! echo $sub | grep -q '#time ' ; then
#     echo "ABORTING - #time flag missing in subject"
#     exit 1
# fi

