#!/bin/sh

git diff --cached --name-only --diff-filter=ACM | xargs -n 1 -I {} sed -i 's/\xc2\xa0/ /g' {}
git diff --cached --name-only --diff-filter=ACM | xargs -n 1 -I {} dos2unix {}
git diff --cached --name-only --diff-filter=ACM | xargs -I {} git add {}



